name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - test-ci
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  pull_request:

jobs:
  # Push image to Docker Registry
  push:
    runs-on: ubuntu-latest

    steps:
    - name: failed
      run: |
        make test

    - name: always
      if: ${{ always() }}
      run: |
          echo "always"

    - name: next
      run: |
          echo "next"

    - name: always2
      if: ${{ always() }}
      run: |
          echo "always2"
